name = "PlotQuadMesh"
uuid = "f8738a56-6654-4070-8861-884d9be46750"
authors = ["Arjun <arjun.narayanan91@gmail.com> and contributors"]
version = "0.1.0"

[deps]
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"

[compat]
PyPlot = "2"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
